# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'sensor.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGridLayout,
    QGroupBox, QLabel, QLayout, QPlainTextEdit,
    QPushButton, QRadioButton, QScrollArea, QSizePolicy,
    QStackedWidget, QTextBrowser, QVBoxLayout, QWidget)

class Ui_Sensor(object):
    def setupUi(self, Sensor):
        if not Sensor.objectName():
            Sensor.setObjectName(u"Sensor")
        Sensor.resize(1454, 880)
        self.gridLayoutWidget = QWidget(Sensor)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(20, 20, 1411, 881))
        self.dashboard = QGridLayout(self.gridLayoutWidget)
        self.dashboard.setObjectName(u"dashboard")
        self.dashboard.setHorizontalSpacing(14)
        self.dashboard.setVerticalSpacing(12)
        self.dashboard.setContentsMargins(6, 0, 0, 0)
        self.layout_display = QVBoxLayout()
        self.layout_display.setObjectName(u"layout_display")
        self.stackedDisplay = QStackedWidget(self.gridLayoutWidget)
        self.stackedDisplay.setObjectName(u"stackedDisplay")
        self.Values = QWidget()
        self.Values.setObjectName(u"Values")
        self.next = QPushButton(self.Values)
        self.next.setObjectName(u"next")
        self.next.setGeometry(QRect(945, 8, 89, 25))
        self.verticalLayoutWidget_4 = QWidget(self.Values)
        self.verticalLayoutWidget_4.setObjectName(u"verticalLayoutWidget_4")
        self.verticalLayoutWidget_4.setGeometry(QRect(-1, 40, 1041, 621))
        self.layout_values = QVBoxLayout(self.verticalLayoutWidget_4)
        self.layout_values.setObjectName(u"layout_values")
        self.layout_values.setContentsMargins(0, 0, 0, 0)
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.status = QGroupBox(self.verticalLayoutWidget_4)
        self.status.setObjectName(u"status")
        self.labelGPSFix = QLabel(self.status)
        self.labelGPSFix.setObjectName(u"labelGPSFix")
        self.labelGPSFix.setGeometry(QRect(10, 120, 67, 17))
        self.hAccu = QPlainTextEdit(self.status)
        self.hAccu.setObjectName(u"hAccu")
        self.hAccu.setGeometry(QRect(90, 30, 161, 21))
#if QT_CONFIG(tooltip)
        self.hAccu.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.hAccu.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.hAccu.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.hAccu.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.hAccu.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.hAccu.setReadOnly(True)
        self.labelhAccu = QLabel(self.status)
        self.labelhAccu.setObjectName(u"labelhAccu")
        self.labelhAccu.setGeometry(QRect(10, 30, 67, 17))
        self.GPSFix = QPlainTextEdit(self.status)
        self.GPSFix.setObjectName(u"GPSFix")
        self.GPSFix.setGeometry(QRect(90, 120, 161, 21))
#if QT_CONFIG(tooltip)
        self.GPSFix.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.GPSFix.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.GPSFix.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.GPSFix.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.GPSFix.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.GPSFix.setReadOnly(True)
        self.vAccu = QPlainTextEdit(self.status)
        self.vAccu.setObjectName(u"vAccu")
        self.vAccu.setGeometry(QRect(90, 60, 161, 21))
#if QT_CONFIG(tooltip)
        self.vAccu.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.vAccu.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.vAccu.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.vAccu.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.vAccu.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.vAccu.setReadOnly(True)
        self.labelvAccu = QLabel(self.status)
        self.labelvAccu.setObjectName(u"labelvAccu")
        self.labelvAccu.setGeometry(QRect(10, 60, 81, 17))
        self.labelacc3D = QLabel(self.status)
        self.labelacc3D.setObjectName(u"labelacc3D")
        self.labelacc3D.setGeometry(QRect(10, 90, 67, 17))
        self.acc3D = QPlainTextEdit(self.status)
        self.acc3D.setObjectName(u"acc3D")
        self.acc3D.setGeometry(QRect(90, 90, 161, 21))
#if QT_CONFIG(tooltip)
        self.acc3D.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.acc3D.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.acc3D.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.acc3D.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.acc3D.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.acc3D.setReadOnly(True)
        self.VDOP = QPlainTextEdit(self.status)
        self.VDOP.setObjectName(u"VDOP")
        self.VDOP.setGeometry(QRect(90, 210, 161, 21))
#if QT_CONFIG(tooltip)
        self.VDOP.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.VDOP.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.VDOP.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.VDOP.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.VDOP.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.VDOP.setReadOnly(True)
        self.PDOP = QPlainTextEdit(self.status)
        self.PDOP.setObjectName(u"PDOP")
        self.PDOP.setGeometry(QRect(90, 240, 161, 21))
#if QT_CONFIG(tooltip)
        self.PDOP.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.PDOP.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.PDOP.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.PDOP.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.PDOP.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.PDOP.setReadOnly(True)
        self.numSat = QPlainTextEdit(self.status)
        self.numSat.setObjectName(u"numSat")
        self.numSat.setGeometry(QRect(90, 150, 161, 21))
#if QT_CONFIG(tooltip)
        self.numSat.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.numSat.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.numSat.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.numSat.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.numSat.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.numSat.setReadOnly(True)
        self.labelPDOP = QLabel(self.status)
        self.labelPDOP.setObjectName(u"labelPDOP")
        self.labelPDOP.setGeometry(QRect(10, 240, 67, 17))
        self.labelHDOP = QLabel(self.status)
        self.labelHDOP.setObjectName(u"labelHDOP")
        self.labelHDOP.setGeometry(QRect(10, 180, 81, 17))
        self.labelVDOP = QLabel(self.status)
        self.labelVDOP.setObjectName(u"labelVDOP")
        self.labelVDOP.setGeometry(QRect(10, 210, 67, 17))
        self.labelnumSat = QLabel(self.status)
        self.labelnumSat.setObjectName(u"labelnumSat")
        self.labelnumSat.setGeometry(QRect(10, 150, 67, 17))
        self.HDOP = QPlainTextEdit(self.status)
        self.HDOP.setObjectName(u"HDOP")
        self.HDOP.setGeometry(QRect(90, 180, 161, 21))
#if QT_CONFIG(tooltip)
        self.HDOP.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.HDOP.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.HDOP.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.HDOP.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.HDOP.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.HDOP.setReadOnly(True)
        self.labelFusionMode = QLabel(self.status)
        self.labelFusionMode.setObjectName(u"labelFusionMode")
        self.labelFusionMode.setGeometry(QRect(10, 270, 67, 17))
        self.fusionMode = QPlainTextEdit(self.status)
        self.fusionMode.setObjectName(u"fusionMode")
        self.fusionMode.setGeometry(QRect(90, 270, 161, 21))
#if QT_CONFIG(tooltip)
        self.fusionMode.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.fusionMode.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.fusionMode.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.fusionMode.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.fusionMode.setReadOnly(True)
        self.labelimuStatus = QLabel(self.status)
        self.labelimuStatus.setObjectName(u"labelimuStatus")
        self.labelimuStatus.setGeometry(QRect(10, 300, 67, 17))
        self.imuStatus = QPlainTextEdit(self.status)
        self.imuStatus.setObjectName(u"imuStatus")
        self.imuStatus.setGeometry(QRect(90, 300, 161, 21))
#if QT_CONFIG(tooltip)
        self.imuStatus.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.imuStatus.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.imuStatus.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.imuStatus.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.imuStatus.setReadOnly(True)
        self.labelRollAccu = QLabel(self.status)
        self.labelRollAccu.setObjectName(u"labelRollAccu")
        self.labelRollAccu.setGeometry(QRect(10, 330, 67, 17))
        self.rollAccu = QPlainTextEdit(self.status)
        self.rollAccu.setObjectName(u"rollAccu")
        self.rollAccu.setGeometry(QRect(90, 330, 161, 21))
#if QT_CONFIG(tooltip)
        self.rollAccu.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.rollAccu.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rollAccu.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rollAccu.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.rollAccu.setReadOnly(True)
        self.labelPitchAccu = QLabel(self.status)
        self.labelPitchAccu.setObjectName(u"labelPitchAccu")
        self.labelPitchAccu.setGeometry(QRect(10, 360, 67, 17))
        self.pitchAccu = QPlainTextEdit(self.status)
        self.pitchAccu.setObjectName(u"pitchAccu")
        self.pitchAccu.setGeometry(QRect(90, 360, 161, 21))
#if QT_CONFIG(tooltip)
        self.pitchAccu.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.pitchAccu.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.pitchAccu.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.pitchAccu.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.pitchAccu.setReadOnly(True)
        self.labelYawAccu = QLabel(self.status)
        self.labelYawAccu.setObjectName(u"labelYawAccu")
        self.labelYawAccu.setGeometry(QRect(10, 390, 67, 17))
        self.yawAccu = QPlainTextEdit(self.status)
        self.yawAccu.setObjectName(u"yawAccu")
        self.yawAccu.setGeometry(QRect(90, 390, 161, 21))
#if QT_CONFIG(tooltip)
        self.yawAccu.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.yawAccu.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.yawAccu.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.yawAccu.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.yawAccu.setReadOnly(True)

        self.gridLayout.addWidget(self.status, 1, 0, 2, 1)

        self.quaternion = QGroupBox(self.verticalLayoutWidget_4)
        self.quaternion.setObjectName(u"quaternion")
        self.quatX = QPlainTextEdit(self.quaternion)
        self.quatX.setObjectName(u"quatX")
        self.quatX.setGeometry(QRect(90, 30, 161, 21))
#if QT_CONFIG(tooltip)
        self.quatX.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.quatX.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.quatX.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.quatX.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.quatX.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.quatX.setReadOnly(True)
        self.labelQX = QLabel(self.quaternion)
        self.labelQX.setObjectName(u"labelQX")
        self.labelQX.setGeometry(QRect(10, 30, 67, 17))
        self.quatY = QPlainTextEdit(self.quaternion)
        self.quatY.setObjectName(u"quatY")
        self.quatY.setGeometry(QRect(90, 60, 161, 21))
#if QT_CONFIG(tooltip)
        self.quatY.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.quatY.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.quatY.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.quatY.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.quatY.setReadOnly(True)
        self.labelQY = QLabel(self.quaternion)
        self.labelQY.setObjectName(u"labelQY")
        self.labelQY.setGeometry(QRect(10, 60, 81, 17))
        self.labelQZ = QLabel(self.quaternion)
        self.labelQZ.setObjectName(u"labelQZ")
        self.labelQZ.setGeometry(QRect(10, 90, 67, 17))
        self.quatZ = QPlainTextEdit(self.quaternion)
        self.quatZ.setObjectName(u"quatZ")
        self.quatZ.setGeometry(QRect(90, 90, 161, 21))
#if QT_CONFIG(tooltip)
        self.quatZ.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.quatZ.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.quatZ.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.quatZ.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.quatZ.setReadOnly(True)
        self.quatW = QPlainTextEdit(self.quaternion)
        self.quatW.setObjectName(u"quatW")
        self.quatW.setGeometry(QRect(90, 120, 161, 21))
#if QT_CONFIG(tooltip)
        self.quatW.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.quatW.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.quatW.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.quatW.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.quatW.setReadOnly(True)
        self.labelQW = QLabel(self.quaternion)
        self.labelQW.setObjectName(u"labelQW")
        self.labelQW.setGeometry(QRect(10, 120, 67, 17))

        self.gridLayout.addWidget(self.quaternion, 2, 2, 1, 1)

        self.timeGPS = QGroupBox(self.verticalLayoutWidget_4)
        self.timeGPS.setObjectName(u"timeGPS")
        self.labelSystemGPS = QLabel(self.timeGPS)
        self.labelSystemGPS.setObjectName(u"labelSystemGPS")
        self.labelSystemGPS.setGeometry(QRect(10, 30, 67, 17))
        self.labelGPSTime = QLabel(self.timeGPS)
        self.labelGPSTime.setObjectName(u"labelGPSTime")
        self.labelGPSTime.setGeometry(QRect(10, 60, 67, 17))
        self.systemTimeGPS = QPlainTextEdit(self.timeGPS)
        self.systemTimeGPS.setObjectName(u"systemTimeGPS")
        self.systemTimeGPS.setGeometry(QRect(70, 30, 181, 21))
#if QT_CONFIG(tooltip)
        self.systemTimeGPS.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.systemTimeGPS.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.systemTimeGPS.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.systemTimeGPS.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.systemTimeGPS.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.systemTimeGPS.setReadOnly(True)
        self.GPSTime = QPlainTextEdit(self.timeGPS)
        self.GPSTime.setObjectName(u"GPSTime")
        self.GPSTime.setGeometry(QRect(70, 60, 181, 21))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GPSTime.sizePolicy().hasHeightForWidth())
        self.GPSTime.setSizePolicy(sizePolicy)
#if QT_CONFIG(tooltip)
        self.GPSTime.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.GPSTime.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.GPSTime.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.GPSTime.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.GPSTime.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.GPSTime.setReadOnly(True)

        self.gridLayout.addWidget(self.timeGPS, 0, 0, 1, 1)

        self.angular = QGroupBox(self.verticalLayoutWidget_4)
        self.angular.setObjectName(u"angular")
        self.gyroX = QPlainTextEdit(self.angular)
        self.gyroX.setObjectName(u"gyroX")
        self.gyroX.setGeometry(QRect(90, 30, 161, 21))
#if QT_CONFIG(tooltip)
        self.gyroX.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.gyroX.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.gyroX.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.gyroX.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.gyroX.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.gyroX.setReadOnly(True)
        self.labelGyroX = QLabel(self.angular)
        self.labelGyroX.setObjectName(u"labelGyroX")
        self.labelGyroX.setGeometry(QRect(10, 30, 67, 17))
        self.gyroY = QPlainTextEdit(self.angular)
        self.gyroY.setObjectName(u"gyroY")
        self.gyroY.setGeometry(QRect(90, 60, 161, 21))
#if QT_CONFIG(tooltip)
        self.gyroY.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.gyroY.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.gyroY.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.gyroY.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.gyroY.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.gyroY.setReadOnly(True)
        self.labelGryoY = QLabel(self.angular)
        self.labelGryoY.setObjectName(u"labelGryoY")
        self.labelGryoY.setGeometry(QRect(10, 60, 81, 17))
        self.labelGryoZ = QLabel(self.angular)
        self.labelGryoZ.setObjectName(u"labelGryoZ")
        self.labelGryoZ.setGeometry(QRect(10, 90, 67, 17))
        self.gyroZ = QPlainTextEdit(self.angular)
        self.gyroZ.setObjectName(u"gyroZ")
        self.gyroZ.setGeometry(QRect(90, 90, 161, 21))
#if QT_CONFIG(tooltip)
        self.gyroZ.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.gyroZ.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.gyroZ.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.gyroZ.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.gyroZ.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.gyroZ.setReadOnly(True)

        self.gridLayout.addWidget(self.angular, 1, 2, 1, 1)

        self.calibration = QGroupBox(self.verticalLayoutWidget_4)
        self.calibration.setObjectName(u"calibration")
        self.calibration.setMinimumSize(QSize(0, 214))
        self.calibGyroZ = QPlainTextEdit(self.calibration)
        self.calibGyroZ.setObjectName(u"calibGyroZ")
        self.calibGyroZ.setGeometry(QRect(90, 90, 161, 21))
#if QT_CONFIG(tooltip)
        self.calibGyroZ.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.calibGyroZ.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.calibGyroZ.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.calibGyroZ.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.calibGyroZ.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.calibGyroZ.setReadOnly(True)
        self.calibAccX = QPlainTextEdit(self.calibration)
        self.calibAccX.setObjectName(u"calibAccX")
        self.calibAccX.setGeometry(QRect(90, 120, 161, 21))
#if QT_CONFIG(tooltip)
        self.calibAccX.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.calibAccX.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.calibAccX.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.calibAccX.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.calibAccX.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.calibAccX.setReadOnly(True)
        self.calibGyroX = QPlainTextEdit(self.calibration)
        self.calibGyroX.setObjectName(u"calibGyroX")
        self.calibGyroX.setGeometry(QRect(90, 30, 161, 21))
#if QT_CONFIG(tooltip)
        self.calibGyroX.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.calibGyroX.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.calibGyroX.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.calibGyroX.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.calibGyroX.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.calibGyroX.setReadOnly(True)
        self.labelAccX_1 = QLabel(self.calibration)
        self.labelAccX_1.setObjectName(u"labelAccX_1")
        self.labelAccX_1.setGeometry(QRect(10, 120, 67, 17))
        self.labelGyroY_1 = QLabel(self.calibration)
        self.labelGyroY_1.setObjectName(u"labelGyroY_1")
        self.labelGyroY_1.setGeometry(QRect(10, 60, 81, 17))
        self.labelGyroZ_1 = QLabel(self.calibration)
        self.labelGyroZ_1.setObjectName(u"labelGyroZ_1")
        self.labelGyroZ_1.setGeometry(QRect(10, 90, 67, 17))
        self.labelGyroX_1 = QLabel(self.calibration)
        self.labelGyroX_1.setObjectName(u"labelGyroX_1")
        self.labelGyroX_1.setGeometry(QRect(10, 30, 67, 17))
        self.labelAccZ_1 = QLabel(self.calibration)
        self.labelAccZ_1.setObjectName(u"labelAccZ_1")
        self.labelAccZ_1.setGeometry(QRect(10, 180, 81, 17))
        self.calibAccZ = QPlainTextEdit(self.calibration)
        self.calibAccZ.setObjectName(u"calibAccZ")
        self.calibAccZ.setGeometry(QRect(90, 180, 161, 21))
#if QT_CONFIG(tooltip)
        self.calibAccZ.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.calibAccZ.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.calibAccZ.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.calibAccZ.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.calibAccZ.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.calibAccZ.setReadOnly(True)
        self.labelAccY_1 = QLabel(self.calibration)
        self.labelAccY_1.setObjectName(u"labelAccY_1")
        self.labelAccY_1.setGeometry(QRect(10, 150, 67, 17))
        self.calibGyroY = QPlainTextEdit(self.calibration)
        self.calibGyroY.setObjectName(u"calibGyroY")
        self.calibGyroY.setGeometry(QRect(90, 60, 161, 21))
#if QT_CONFIG(tooltip)
        self.calibGyroY.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.calibGyroY.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.calibGyroY.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.calibGyroY.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.calibGyroY.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.calibGyroY.setReadOnly(True)
        self.calibAccY = QPlainTextEdit(self.calibration)
        self.calibAccY.setObjectName(u"calibAccY")
        self.calibAccY.setGeometry(QRect(90, 150, 161, 21))
#if QT_CONFIG(tooltip)
        self.calibAccY.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.calibAccY.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.calibAccY.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.calibAccY.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.calibAccY.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.calibAccY.setReadOnly(True)

        self.gridLayout.addWidget(self.calibration, 1, 1, 1, 1)

        self.gps = QGroupBox(self.verticalLayoutWidget_4)
        self.gps.setObjectName(u"gps")
        self.longitude = QPlainTextEdit(self.gps)
        self.longitude.setObjectName(u"longitude")
        self.longitude.setGeometry(QRect(90, 60, 161, 21))
#if QT_CONFIG(tooltip)
        self.longitude.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.longitude.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.longitude.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.longitude.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.longitude.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.longitude.setReadOnly(True)
        self.labelLatitude = QLabel(self.gps)
        self.labelLatitude.setObjectName(u"labelLatitude")
        self.labelLatitude.setGeometry(QRect(10, 30, 67, 17))
        self.labelLongitude = QLabel(self.gps)
        self.labelLongitude.setObjectName(u"labelLongitude")
        self.labelLongitude.setGeometry(QRect(10, 60, 81, 17))
        self.latitude = QPlainTextEdit(self.gps)
        self.latitude.setObjectName(u"latitude")
        self.latitude.setGeometry(QRect(90, 30, 161, 21))
#if QT_CONFIG(tooltip)
        self.latitude.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.latitude.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.latitude.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.latitude.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.latitude.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.latitude.setReadOnly(True)
        self.altitude = QPlainTextEdit(self.gps)
        self.altitude.setObjectName(u"altitude")
        self.altitude.setGeometry(QRect(90, 90, 161, 21))
#if QT_CONFIG(tooltip)
        self.altitude.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.altitude.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.altitude.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.altitude.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.altitude.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.altitude.setReadOnly(True)
        self.labelAltitude = QLabel(self.gps)
        self.labelAltitude.setObjectName(u"labelAltitude")
        self.labelAltitude.setGeometry(QRect(10, 90, 67, 17))
        self.labelHeading = QLabel(self.gps)
        self.labelHeading.setObjectName(u"labelHeading")
        self.labelHeading.setGeometry(QRect(10, 120, 67, 17))
        self.heading = QPlainTextEdit(self.gps)
        self.heading.setObjectName(u"heading")
        self.heading.setGeometry(QRect(90, 120, 161, 21))
#if QT_CONFIG(tooltip)
        self.heading.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.heading.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.heading.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.heading.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.heading.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.heading.setReadOnly(True)
        self.labelFix = QLabel(self.gps)
        self.labelFix.setObjectName(u"labelFix")
        self.labelFix.setGeometry(QRect(10, 150, 67, 17))
        self.fix = QPlainTextEdit(self.gps)
        self.fix.setObjectName(u"fix")
        self.fix.setGeometry(QRect(90, 150, 161, 21))
#if QT_CONFIG(tooltip)
        self.fix.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.fix.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.fix.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.fix.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.fix.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.fix.setReadOnly(True)

        self.gridLayout.addWidget(self.gps, 0, 1, 1, 1)

        self.acceleration = QGroupBox(self.verticalLayoutWidget_4)
        self.acceleration.setObjectName(u"acceleration")
        self.AccX = QPlainTextEdit(self.acceleration)
        self.AccX.setObjectName(u"AccX")
        self.AccX.setGeometry(QRect(90, 30, 161, 21))
#if QT_CONFIG(tooltip)
        self.AccX.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.AccX.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.AccX.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.AccX.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.AccX.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.AccX.setReadOnly(True)
        self.labelAccX = QLabel(self.acceleration)
        self.labelAccX.setObjectName(u"labelAccX")
        self.labelAccX.setGeometry(QRect(10, 30, 67, 17))
        self.AccY = QPlainTextEdit(self.acceleration)
        self.AccY.setObjectName(u"AccY")
        self.AccY.setGeometry(QRect(90, 60, 161, 21))
#if QT_CONFIG(tooltip)
        self.AccY.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.AccY.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.AccY.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.AccY.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.AccY.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.AccY.setReadOnly(True)
        self.labelAccY = QLabel(self.acceleration)
        self.labelAccY.setObjectName(u"labelAccY")
        self.labelAccY.setGeometry(QRect(10, 60, 81, 17))
        self.labelAccZ = QLabel(self.acceleration)
        self.labelAccZ.setObjectName(u"labelAccZ")
        self.labelAccZ.setGeometry(QRect(10, 90, 67, 17))
        self.AccZ = QPlainTextEdit(self.acceleration)
        self.AccZ.setObjectName(u"AccZ")
        self.AccZ.setGeometry(QRect(90, 90, 161, 21))
#if QT_CONFIG(tooltip)
        self.AccZ.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.AccZ.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.AccZ.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.AccZ.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.AccZ.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.AccZ.setReadOnly(True)

        self.gridLayout.addWidget(self.acceleration, 1, 3, 1, 1)

        self.timeIMU = QGroupBox(self.verticalLayoutWidget_4)
        self.timeIMU.setObjectName(u"timeIMU")
        self.labelTimeIMU = QLabel(self.timeIMU)
        self.labelTimeIMU.setObjectName(u"labelTimeIMU")
        self.labelTimeIMU.setGeometry(QRect(10, 30, 67, 17))
        self.labeIMU = QLabel(self.timeIMU)
        self.labeIMU.setObjectName(u"labeIMU")
        self.labeIMU.setGeometry(QRect(10, 60, 67, 17))
        self.systemTimeIMU = QPlainTextEdit(self.timeIMU)
        self.systemTimeIMU.setObjectName(u"systemTimeIMU")
        self.systemTimeIMU.setGeometry(QRect(70, 30, 181, 21))
#if QT_CONFIG(tooltip)
        self.systemTimeIMU.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.systemTimeIMU.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.systemTimeIMU.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.systemTimeIMU.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.systemTimeIMU.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.systemTimeIMU.setReadOnly(True)
        self.TimeIMU = QPlainTextEdit(self.timeIMU)
        self.TimeIMU.setObjectName(u"TimeIMU")
        self.TimeIMU.setGeometry(QRect(70, 60, 181, 21))
        sizePolicy.setHeightForWidth(self.TimeIMU.sizePolicy().hasHeightForWidth())
        self.TimeIMU.setSizePolicy(sizePolicy)
#if QT_CONFIG(tooltip)
        self.TimeIMU.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.TimeIMU.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.TimeIMU.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.TimeIMU.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.TimeIMU.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.TimeIMU.setReadOnly(True)

        self.gridLayout.addWidget(self.timeIMU, 0, 2, 1, 1)

        self.angle = QGroupBox(self.verticalLayoutWidget_4)
        self.angle.setObjectName(u"angle")
        self.roll = QPlainTextEdit(self.angle)
        self.roll.setObjectName(u"roll")
        self.roll.setGeometry(QRect(90, 30, 161, 21))
#if QT_CONFIG(tooltip)
        self.roll.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.roll.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.roll.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.roll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.roll.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.roll.setReadOnly(True)
        self.labelRoll = QLabel(self.angle)
        self.labelRoll.setObjectName(u"labelRoll")
        self.labelRoll.setGeometry(QRect(10, 30, 67, 17))
        self.pitch = QPlainTextEdit(self.angle)
        self.pitch.setObjectName(u"pitch")
        self.pitch.setGeometry(QRect(90, 60, 161, 21))
#if QT_CONFIG(tooltip)
        self.pitch.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.pitch.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.pitch.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.pitch.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.pitch.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.pitch.setReadOnly(True)
        self.labelPitch = QLabel(self.angle)
        self.labelPitch.setObjectName(u"labelPitch")
        self.labelPitch.setGeometry(QRect(10, 60, 81, 17))
        self.labelYaw = QLabel(self.angle)
        self.labelYaw.setObjectName(u"labelYaw")
        self.labelYaw.setGeometry(QRect(10, 90, 67, 17))
        self.yaw = QPlainTextEdit(self.angle)
        self.yaw.setObjectName(u"yaw")
        self.yaw.setGeometry(QRect(90, 90, 161, 21))
#if QT_CONFIG(tooltip)
        self.yaw.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.yaw.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.yaw.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.yaw.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.yaw.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.yaw.setReadOnly(True)

        self.gridLayout.addWidget(self.angle, 0, 3, 1, 1)

        self.groupBox = QGroupBox(self.verticalLayoutWidget_4)
        self.groupBox.setObjectName(u"groupBox")
        self.diffAge = QPlainTextEdit(self.groupBox)
        self.diffAge.setObjectName(u"diffAge")
        self.diffAge.setGeometry(QRect(90, 30, 161, 21))
#if QT_CONFIG(tooltip)
        self.diffAge.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.diffAge.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.diffAge.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.diffAge.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.diffAge.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.diffAge.setReadOnly(True)
        self.labelDiffAge = QLabel(self.groupBox)
        self.labelDiffAge.setObjectName(u"labelDiffAge")
        self.labelDiffAge.setGeometry(QRect(10, 30, 81, 17))
        self.diffStation = QPlainTextEdit(self.groupBox)
        self.diffStation.setObjectName(u"diffStation")
        self.diffStation.setGeometry(QRect(90, 60, 161, 21))
#if QT_CONFIG(tooltip)
        self.diffStation.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.diffStation.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.diffStation.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.diffStation.setLineWrapMode(QPlainTextEdit.LineWrapMode.NoWrap)
        self.diffStation.setReadOnly(True)
        self.labelDiffStation = QLabel(self.groupBox)
        self.labelDiffStation.setObjectName(u"labelDiffStation")
        self.labelDiffStation.setGeometry(QRect(10, 60, 81, 17))

        self.gridLayout.addWidget(self.groupBox, 2, 1, 1, 1)


        self.layout_values.addLayout(self.gridLayout)

        self.Label_values = QLabel(self.Values)
        self.Label_values.setObjectName(u"Label_values")
        self.Label_values.setGeometry(QRect(10, 0, 1059, 36))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Maximum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.Label_values.sizePolicy().hasHeightForWidth())
        self.Label_values.setSizePolicy(sizePolicy1)
        self.Label_values.setMaximumSize(QSize(1209, 16777215))
        font = QFont()
        font.setPointSize(24)
        self.Label_values.setFont(font)
        self.stackedDisplay.addWidget(self.Values)
        self.Map = QWidget()
        self.Map.setObjectName(u"Map")
        self.verticalLayoutWidget_3 = QWidget(self.Map)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(-1, 40, 1041, 621))
        self.layout_map = QVBoxLayout(self.verticalLayoutWidget_3)
        self.layout_map.setObjectName(u"layout_map")
        self.layout_map.setContentsMargins(0, 0, 0, 0)
        self.prev = QPushButton(self.Map)
        self.prev.setObjectName(u"prev")
        self.prev.setGeometry(QRect(945, 8, 89, 25))
        self.Label_map = QLabel(self.Map)
        self.Label_map.setObjectName(u"Label_map")
        self.Label_map.setGeometry(QRect(10, 0, 1059, 36))
        sizePolicy1.setHeightForWidth(self.Label_map.sizePolicy().hasHeightForWidth())
        self.Label_map.setSizePolicy(sizePolicy1)
        self.Label_map.setMaximumSize(QSize(1209, 16777215))
        self.Label_map.setFont(font)
        self.stackedDisplay.addWidget(self.Map)
        self.Label_map.raise_()
        self.verticalLayoutWidget_3.raise_()
        self.prev.raise_()

        self.layout_display.addWidget(self.stackedDisplay)


        self.dashboard.addLayout(self.layout_display, 0, 0, 1, 1)

        self.layout_setting = QVBoxLayout()
        self.layout_setting.setObjectName(u"layout_setting")
        self.layout_setting.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout_2 = QGridLayout()
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.ethernet = QGroupBox(self.gridLayoutWidget)
        self.ethernet.setObjectName(u"ethernet")
        self.btnPandarView = QPushButton(self.ethernet)
        self.btnPandarView.setObjectName(u"btnPandarView")
        self.btnPandarView.setGeometry(QRect(80, 144, 221, 25))
        self.ethernetPort = QComboBox(self.ethernet)
        self.ethernetPort.setObjectName(u"ethernetPort")
        self.ethernetPort.setGeometry(QRect(80, 30, 221, 22))
        self.ethernetLabel = QLabel(self.ethernet)
        self.ethernetLabel.setObjectName(u"ethernetLabel")
        self.ethernetLabel.setGeometry(QRect(10, 30, 81, 20))
        self.btnPtpd = QPushButton(self.ethernet)
        self.btnPtpd.setObjectName(u"btnPtpd")
        self.btnPtpd.setGeometry(QRect(80, 104, 221, 25))
        self.btnLidarStatus = QPushButton(self.ethernet)
        self.btnLidarStatus.setObjectName(u"btnLidarStatus")
        self.btnLidarStatus.setGeometry(QRect(80, 184, 221, 25))
        self.btnIPV4 = QPushButton(self.ethernet)
        self.btnIPV4.setObjectName(u"btnIPV4")
        self.btnIPV4.setGeometry(QRect(80, 64, 221, 25))

        self.gridLayout_2.addWidget(self.ethernet, 1, 0, 1, 1)

        self.serial_connect = QGroupBox(self.gridLayoutWidget)
        self.serial_connect.setObjectName(u"serial_connect")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.serial_connect.sizePolicy().hasHeightForWidth())
        self.serial_connect.setSizePolicy(sizePolicy2)
        self.serial_connect.setMinimumSize(QSize(345, 250))
        self.gpsSerial = QComboBox(self.serial_connect)
        self.gpsSerial.setObjectName(u"gpsSerial")
        self.gpsSerial.setGeometry(QRect(88, 50, 101, 22))
        self.serialConnectionButton = QPushButton(self.serial_connect)
        self.serialConnectionButton.setObjectName(u"serialConnectionButton")
        self.serialConnectionButton.setGeometry(QRect(140, 180, 80, 22))
        self.serialTerminationButton = QPushButton(self.serial_connect)
        self.serialTerminationButton.setObjectName(u"serialTerminationButton")
        self.serialTerminationButton.setEnabled(False)
        self.serialTerminationButton.setGeometry(QRect(230, 180, 80, 22))
        self.gpsLabel = QLabel(self.serial_connect)
        self.gpsLabel.setObjectName(u"gpsLabel")
        self.gpsLabel.setGeometry(QRect(118, 30, 41, 17))
        self.baudLabel = QLabel(self.serial_connect)
        self.baudLabel.setObjectName(u"baudLabel")
        self.baudLabel.setGeometry(QRect(10, 80, 81, 20))
        self.baudGPS = QComboBox(self.serial_connect)
        self.baudGPS.addItem("")
        self.baudGPS.addItem("")
        self.baudGPS.addItem("")
        self.baudGPS.addItem("")
        self.baudGPS.addItem("")
        self.baudGPS.addItem("")
        self.baudGPS.addItem("")
        self.baudGPS.addItem("")
        self.baudGPS.addItem("")
        self.baudGPS.addItem("")
        self.baudGPS.addItem("")
        self.baudGPS.addItem("")
        self.baudGPS.addItem("")
        self.baudGPS.addItem("")
        self.baudGPS.setObjectName(u"baudGPS")
        self.baudGPS.setEnabled(True)
        self.baudGPS.setGeometry(QRect(88, 80, 101, 25))
        self.baudGPS.setEditable(False)
        self.baudGPS.setMinimumContentsLength(0)
        self.serialLabel = QLabel(self.serial_connect)
        self.serialLabel.setObjectName(u"serialLabel")
        self.serialLabel.setGeometry(QRect(10, 50, 81, 20))
        self.baudIMU = QComboBox(self.serial_connect)
        self.baudIMU.addItem("")
        self.baudIMU.addItem("")
        self.baudIMU.addItem("")
        self.baudIMU.addItem("")
        self.baudIMU.addItem("")
        self.baudIMU.addItem("")
        self.baudIMU.addItem("")
        self.baudIMU.addItem("")
        self.baudIMU.addItem("")
        self.baudIMU.addItem("")
        self.baudIMU.addItem("")
        self.baudIMU.addItem("")
        self.baudIMU.addItem("")
        self.baudIMU.addItem("")
        self.baudIMU.setObjectName(u"baudIMU")
        self.baudIMU.setGeometry(QRect(208, 80, 101, 25))
        self.imuLabel = QLabel(self.serial_connect)
        self.imuLabel.setObjectName(u"imuLabel")
        self.imuLabel.setGeometry(QRect(238, 30, 41, 17))
        self.imuSerial = QComboBox(self.serial_connect)
        self.imuSerial.setObjectName(u"imuSerial")
        self.imuSerial.setGeometry(QRect(208, 50, 101, 22))
        self.typeLabel = QLabel(self.serial_connect)
        self.typeLabel.setObjectName(u"typeLabel")
        self.typeLabel.setGeometry(QRect(10, 110, 81, 20))
        self.imuType = QComboBox(self.serial_connect)
        self.imuType.setObjectName(u"imuType")
        self.imuType.setGeometry(QRect(208, 110, 101, 22))
        self.gpsType = QComboBox(self.serial_connect)
        self.gpsType.setObjectName(u"gpsType")
        self.gpsType.setGeometry(QRect(88, 110, 101, 22))
        self.recordingFolderbtn = QPushButton(self.serial_connect)
        self.recordingFolderbtn.setObjectName(u"recordingFolderbtn")
        self.recordingFolderbtn.setGeometry(QRect(140, 210, 171, 25))
        self.ntripConnection = QCheckBox(self.serial_connect)
        self.ntripConnection.setObjectName(u"ntripConnection")
        self.ntripConnection.setGeometry(QRect(160, 150, 151, 23))
        self.ntripConnection.setChecked(True)
        self.saveButton = QCheckBox(self.serial_connect)
        self.saveButton.setObjectName(u"saveButton")
        self.saveButton.setGeometry(QRect(40, 150, 92, 23))
        self.saveButton.setChecked(True)
        self.saveButton.setTristate(False)

        self.gridLayout_2.addWidget(self.serial_connect, 0, 0, 1, 1)

        self.bluetooth = QGroupBox(self.gridLayoutWidget)
        self.bluetooth.setObjectName(u"bluetooth")
        self.bluetooth.setMaximumSize(QSize(16777215, 175))
        self.BLEConnectionButton = QPushButton(self.bluetooth)
        self.BLEConnectionButton.setObjectName(u"BLEConnectionButton")
        self.BLEConnectionButton.setGeometry(QRect(140, 73, 80, 22))
        self.BLETerminationButton = QPushButton(self.bluetooth)
        self.BLETerminationButton.setObjectName(u"BLETerminationButton")
        self.BLETerminationButton.setEnabled(False)
        self.BLETerminationButton.setGeometry(QRect(230, 73, 80, 22))
        self.saveButton_2 = QRadioButton(self.bluetooth)
        self.saveButton_2.setObjectName(u"saveButton_2")
        self.saveButton_2.setGeometry(QRect(10, 73, 141, 23))
        self.saveButton_2.setChecked(True)
        self.bleDevice = QComboBox(self.bluetooth)
        self.bleDevice.setObjectName(u"bleDevice")
        self.bleDevice.setGeometry(QRect(89, 40, 221, 22))
        self.bleDeviceLabel = QLabel(self.bluetooth)
        self.bleDeviceLabel.setObjectName(u"bleDeviceLabel")
        self.bleDeviceLabel.setGeometry(QRect(10, 40, 81, 20))
        self.refreshBtn = QPushButton(self.bluetooth)
        self.refreshBtn.setObjectName(u"refreshBtn")
        self.refreshBtn.setGeometry(QRect(140, 104, 171, 25))

        self.gridLayout_2.addWidget(self.bluetooth, 2, 0, 1, 1)


        self.layout_setting.addLayout(self.gridLayout_2)


        self.dashboard.addLayout(self.layout_setting, 0, 1, 1, 1)

        self.scrollArea = QScrollArea(self.gridLayoutWidget)
        self.scrollArea.setObjectName(u"scrollArea")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy3)
        self.scrollArea.setMaximumSize(QSize(16777215, 205))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 1402, 203))
        self.outputScreen = QTextBrowser(self.scrollAreaWidgetContents)
        self.outputScreen.setObjectName(u"outputScreen")
        self.outputScreen.setGeometry(QRect(0, 0, 1401, 180))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.dashboard.addWidget(self.scrollArea, 1, 0, 1, 2)


        self.retranslateUi(Sensor)

        self.baudGPS.setCurrentIndex(11)
        self.baudIMU.setCurrentIndex(11)


        QMetaObject.connectSlotsByName(Sensor)
    # setupUi

    def retranslateUi(self, Sensor):
        Sensor.setWindowTitle(QCoreApplication.translate("Sensor", u"Form", None))
        self.next.setText(QCoreApplication.translate("Sensor", u"Prev", None))
        self.status.setTitle(QCoreApplication.translate("Sensor", u"Status", None))
        self.labelGPSFix.setText(QCoreApplication.translate("Sensor", u"GPS Fix", None))
        self.hAccu.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.labelhAccu.setText(QCoreApplication.translate("Sensor", u"2D HAcc", None))
        self.GPSFix.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.vAccu.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.labelvAccu.setText(QCoreApplication.translate("Sensor", u"2D VAcc", None))
        self.labelacc3D.setText(QCoreApplication.translate("Sensor", u"3D Acc", None))
        self.acc3D.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.VDOP.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.PDOP.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.numSat.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.labelPDOP.setText(QCoreApplication.translate("Sensor", u"PDOP", None))
        self.labelHDOP.setText(QCoreApplication.translate("Sensor", u"HDOP", None))
        self.labelVDOP.setText(QCoreApplication.translate("Sensor", u"VDOP", None))
        self.labelnumSat.setText(QCoreApplication.translate("Sensor", u"Num Sat", None))
        self.HDOP.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.labelFusionMode.setText(QCoreApplication.translate("Sensor", u"Fusion", None))
        self.fusionMode.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.labelimuStatus.setText(QCoreApplication.translate("Sensor", u"IMU Status", None))
        self.imuStatus.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.labelRollAccu.setText(QCoreApplication.translate("Sensor", u"Roll Acc", None))
        self.rollAccu.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.labelPitchAccu.setText(QCoreApplication.translate("Sensor", u"Pitch Acc", None))
        self.pitchAccu.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.labelYawAccu.setText(QCoreApplication.translate("Sensor", u"Yaw Acc", None))
        self.yawAccu.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.quaternion.setTitle(QCoreApplication.translate("Sensor", u"Quaternion", None))
        self.quatX.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.labelQX.setText(QCoreApplication.translate("Sensor", u"Qx", None))
        self.quatY.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.labelQY.setText(QCoreApplication.translate("Sensor", u"Qy", None))
        self.labelQZ.setText(QCoreApplication.translate("Sensor", u"Qz", None))
        self.quatZ.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.quatW.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.labelQW.setText(QCoreApplication.translate("Sensor", u"Qw", None))
        self.timeGPS.setTitle(QCoreApplication.translate("Sensor", u"GPS Time", None))
        self.labelSystemGPS.setText(QCoreApplication.translate("Sensor", u"Time", None))
        self.labelGPSTime.setText(QCoreApplication.translate("Sensor", u"GPS", None))
        self.systemTimeGPS.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.GPSTime.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.angular.setTitle(QCoreApplication.translate("Sensor", u"Angular Velocity", None))
        self.gyroX.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.labelGyroX.setText(QCoreApplication.translate("Sensor", u"Gyro X", None))
        self.gyroY.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.labelGryoY.setText(QCoreApplication.translate("Sensor", u"Gyro Y", None))
        self.labelGryoZ.setText(QCoreApplication.translate("Sensor", u"Gyro Z", None))
        self.gyroZ.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.calibration.setTitle(QCoreApplication.translate("Sensor", u"Calibation Status", None))
        self.calibGyroZ.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.calibAccX.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.calibGyroX.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.labelAccX_1.setText(QCoreApplication.translate("Sensor", u"acc X", None))
        self.labelGyroY_1.setText(QCoreApplication.translate("Sensor", u"gyro Y", None))
        self.labelGyroZ_1.setText(QCoreApplication.translate("Sensor", u"gyro Z", None))
        self.labelGyroX_1.setText(QCoreApplication.translate("Sensor", u"gyro X", None))
        self.labelAccZ_1.setText(QCoreApplication.translate("Sensor", u"acc Z", None))
        self.calibAccZ.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.labelAccY_1.setText(QCoreApplication.translate("Sensor", u"acc Y", None))
        self.calibGyroY.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.calibAccY.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.gps.setTitle(QCoreApplication.translate("Sensor", u"GPS Data", None))
        self.longitude.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.labelLatitude.setText(QCoreApplication.translate("Sensor", u"Latitude", None))
        self.labelLongitude.setText(QCoreApplication.translate("Sensor", u"Longitude", None))
        self.latitude.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.altitude.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.labelAltitude.setText(QCoreApplication.translate("Sensor", u"Altitude", None))
        self.labelHeading.setText(QCoreApplication.translate("Sensor", u"Heading", None))
        self.heading.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.labelFix.setText(QCoreApplication.translate("Sensor", u"Fix", None))
        self.fix.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.acceleration.setTitle(QCoreApplication.translate("Sensor", u"Acceleration", None))
        self.AccX.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.labelAccX.setText(QCoreApplication.translate("Sensor", u"Acc X", None))
        self.AccY.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.labelAccY.setText(QCoreApplication.translate("Sensor", u"Acc Y", None))
        self.labelAccZ.setText(QCoreApplication.translate("Sensor", u"Acc Z", None))
        self.AccZ.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.timeIMU.setTitle(QCoreApplication.translate("Sensor", u"IMU Time", None))
        self.labelTimeIMU.setText(QCoreApplication.translate("Sensor", u"Time", None))
        self.labeIMU.setText(QCoreApplication.translate("Sensor", u"IMU", None))
        self.systemTimeIMU.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.TimeIMU.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.angle.setTitle(QCoreApplication.translate("Sensor", u"Angle", None))
        self.roll.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.labelRoll.setText(QCoreApplication.translate("Sensor", u"Roll", None))
        self.pitch.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.labelPitch.setText(QCoreApplication.translate("Sensor", u"Pitch", None))
        self.labelYaw.setText(QCoreApplication.translate("Sensor", u"Yaw", None))
        self.yaw.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.groupBox.setTitle(QCoreApplication.translate("Sensor", u"NTRIP Status", None))
        self.diffAge.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.labelDiffAge.setText(QCoreApplication.translate("Sensor", u"Diff Age", None))
        self.diffStation.setPlaceholderText(QCoreApplication.translate("Sensor", u"0", None))
        self.labelDiffStation.setText(QCoreApplication.translate("Sensor", u"Diff Station", None))
        self.Label_values.setText(QCoreApplication.translate("Sensor", u"Values", None))
        self.prev.setText(QCoreApplication.translate("Sensor", u"Next", None))
        self.Label_map.setText(QCoreApplication.translate("Sensor", u"Map", None))
        self.ethernet.setTitle(QCoreApplication.translate("Sensor", u"Ethernet Connection", None))
        self.btnPandarView.setText(QCoreApplication.translate("Sensor", u"PandarView2", None))
        self.ethernetLabel.setText(QCoreApplication.translate("Sensor", u"Port", None))
        self.btnPtpd.setText(QCoreApplication.translate("Sensor", u"Set PTPD", None))
        self.btnLidarStatus.setText(QCoreApplication.translate("Sensor", u"Open Lidar Status Browser", None))
        self.btnIPV4.setText(QCoreApplication.translate("Sensor", u"Set IPV4 Address", None))
        self.serial_connect.setTitle(QCoreApplication.translate("Sensor", u"Serial Connections", None))
        self.serialConnectionButton.setText(QCoreApplication.translate("Sensor", u"Start", None))
        self.serialTerminationButton.setText(QCoreApplication.translate("Sensor", u"Stop", None))
        self.gpsLabel.setText(QCoreApplication.translate("Sensor", u"GPS", None))
        self.baudLabel.setText(QCoreApplication.translate("Sensor", u"Baud", None))
        self.baudGPS.setItemText(0, QCoreApplication.translate("Sensor", u"110", None))
        self.baudGPS.setItemText(1, QCoreApplication.translate("Sensor", u"300", None))
        self.baudGPS.setItemText(2, QCoreApplication.translate("Sensor", u"600", None))
        self.baudGPS.setItemText(3, QCoreApplication.translate("Sensor", u"1200", None))
        self.baudGPS.setItemText(4, QCoreApplication.translate("Sensor", u"2400", None))
        self.baudGPS.setItemText(5, QCoreApplication.translate("Sensor", u"4800", None))
        self.baudGPS.setItemText(6, QCoreApplication.translate("Sensor", u"9600", None))
        self.baudGPS.setItemText(7, QCoreApplication.translate("Sensor", u"14400", None))
        self.baudGPS.setItemText(8, QCoreApplication.translate("Sensor", u"19200", None))
        self.baudGPS.setItemText(9, QCoreApplication.translate("Sensor", u"38400", None))
        self.baudGPS.setItemText(10, QCoreApplication.translate("Sensor", u"57600", None))
        self.baudGPS.setItemText(11, QCoreApplication.translate("Sensor", u"115200", None))
        self.baudGPS.setItemText(12, QCoreApplication.translate("Sensor", u"128000", None))
        self.baudGPS.setItemText(13, QCoreApplication.translate("Sensor", u"256000", None))

        self.serialLabel.setText(QCoreApplication.translate("Sensor", u"Serial", None))
        self.baudIMU.setItemText(0, QCoreApplication.translate("Sensor", u"110", None))
        self.baudIMU.setItemText(1, QCoreApplication.translate("Sensor", u"300", None))
        self.baudIMU.setItemText(2, QCoreApplication.translate("Sensor", u"600", None))
        self.baudIMU.setItemText(3, QCoreApplication.translate("Sensor", u"1200", None))
        self.baudIMU.setItemText(4, QCoreApplication.translate("Sensor", u"2400", None))
        self.baudIMU.setItemText(5, QCoreApplication.translate("Sensor", u"4800", None))
        self.baudIMU.setItemText(6, QCoreApplication.translate("Sensor", u"9600", None))
        self.baudIMU.setItemText(7, QCoreApplication.translate("Sensor", u"14400", None))
        self.baudIMU.setItemText(8, QCoreApplication.translate("Sensor", u"19200", None))
        self.baudIMU.setItemText(9, QCoreApplication.translate("Sensor", u"38400", None))
        self.baudIMU.setItemText(10, QCoreApplication.translate("Sensor", u"57600", None))
        self.baudIMU.setItemText(11, QCoreApplication.translate("Sensor", u"115200", None))
        self.baudIMU.setItemText(12, QCoreApplication.translate("Sensor", u"128000", None))
        self.baudIMU.setItemText(13, QCoreApplication.translate("Sensor", u"256000", None))

        self.imuLabel.setText(QCoreApplication.translate("Sensor", u"IMU", None))
        self.typeLabel.setText(QCoreApplication.translate("Sensor", u"Type", None))
        self.recordingFolderbtn.setText(QCoreApplication.translate("Sensor", u"Open Recording Folder", None))
        self.ntripConnection.setText(QCoreApplication.translate("Sensor", u"NTRIP Connection", None))
        self.saveButton.setText(QCoreApplication.translate("Sensor", u"Save Data", None))
        self.bluetooth.setTitle(QCoreApplication.translate("Sensor", u"Bluetooth Connection", None))
        self.BLEConnectionButton.setText(QCoreApplication.translate("Sensor", u"Start", None))
        self.BLETerminationButton.setText(QCoreApplication.translate("Sensor", u"Stop", None))
        self.saveButton_2.setText(QCoreApplication.translate("Sensor", u"Save Data", None))
        self.bleDeviceLabel.setText(QCoreApplication.translate("Sensor", u"Device", None))
        self.refreshBtn.setText(QCoreApplication.translate("Sensor", u"Refresh List", None))
    # retranslateUi

